# Generated by Django 5.0.4 on 2024-05-04 13:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_by', models.CharField(max_length=255)),
                ('req_by_id', models.CharField(max_length=255)),
                ('req_type', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('approved_timestamp', models.DateTimeField(blank=True, null=True)),
                ('rejected_timestamp', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
                ('file1', models.FileField(upload_to='uploads/')),
                ('att', models.ImageField(upload_to='uploads/')),
                ('status', models.BooleanField(default=True)),
                ('datadeleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogSoftwareIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore')], max_length=10)),
                ('model_name', models.CharField(max_length=255)),
                ('record_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.CharField(max_length=255)),
                ('previous_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
