# Generated by Django 5.0.4 on 2024-04-25 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('check_in_selfie', models.ImageField(blank=True, null=True, upload_to='checkin_selfies/')),
                ('check_out_selfie', models.ImageField(blank=True, null=True, upload_to='checkout_selfies/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
